name: QualityContol

on:
  pull_request:
    branches:
      - main

jobs:
  quality-control:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setupconda

    - name: Install NB-Clean
      run: |
        pip install nb-clean==2.0.2

    - name: Ensure clean notebooks
      run: |
        python .github/workflows/ensure_clean_notebooks.py

<<<<<<< HEAD
    # NOTE: this isn't a comprehensive spellcheck, just common typos
    - name: Spellcheck
      if: always()
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        skip: '.git,qaqc.yml'
        ignore_words_list: slippy,hist
=======
    - name: Install pyspellchecker
      run: |
          pip install pyspellchecker

    - name: Custom Spellcheck with Ignore List
      run: python .github/workflows/spellcheck.py
>>>>>>> bb3679fabc9b231f0a51b8a982f59cb4d1adb432

    # borrowed from https://github.com/ProjectPythia/pythia-foundations/blob/main/.github/workflows/link-checker.yaml
    - name: Disable Notebook Execution Before Linkcheck
      if: always()
      shell: python
      run: |
        import yaml
        with open('./book/_config.yml') as f:
          data = yaml.safe_load(f)
          data['execute']['execute_notebooks'] = 'off'
        with open('./book/_config.yml', 'w') as f:
          yaml.dump(data, f)

    - name: Check External Links
      continue-on-error: true
      if: always()
      run: |
        jb build book --builder linkcheck
